apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: searchlight
  name: bundles.kubepack.dev
spec:
  group: kubepack.dev
  names:
    categories:
    - kubepack
    - appscode
    kind: Bundle
    listKind: BundleList
    plural: bundles
    singular: bundle
  preserveUnknownFields: false
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              items:
                properties:
                  bundle:
                    properties:
                      feature:
                        description: 'One sentence description of feature provided
                          by this addon TODO: Move to a different struct instead of
                          ref'
                        type: string
                      name:
                        type: string
                      url:
                        type: string
                      versions:
                        items:
                          properties:
                            selected:
                              type: boolean
                            version:
                              type: string
                          required:
                          - version
                          type: object
                        type: array
                    required:
                    - feature
                    - name
                    - url
                    - versions
                    type: object
                  feature:
                    type: string
                  oneOf:
                    items:
                      properties:
                        feature:
                          description: 'One sentence description of feature provided
                            by this addon TODO: Move to a different struct instead
                            of ref'
                          type: string
                        name:
                          type: string
                        url:
                          type: string
                        versions:
                          items:
                            properties:
                              selected:
                                type: boolean
                              version:
                                type: string
                            required:
                            - version
                            type: object
                          type: array
                      required:
                      - feature
                      - name
                      - url
                      - versions
                      type: object
                    type: array
                required:
                - feature
                type: object
              type: array
            description:
              description: Description is a brief string description of the Application.
              type: string
            icons:
              description: Icons is an optional list of icons for an application.
                Icon information includes the source, size, and mime type.
              items:
                description: ImageSpec contains information about an image used as
                  an icon.
                properties:
                  size:
                    description: (optional) The size of the image in pixels (e.g.,
                      25x25).
                    type: string
                  src:
                    description: The source for image represented as either an absolute
                      URL to the image or a Data URL containing the image. Data URLs
                      are defined in RFC 2397.
                    type: string
                  type:
                    description: (optional) The mine type of the image (e.g., "image/png").
                    type: string
                required:
                - src
                type: object
              type: array
            keywords:
              description: Keywords is an optional list of key words associated with
                the application (e.g. MySQL, RDBMS, database).
              items:
                type: string
              type: array
            links:
              description: Links are a list of descriptive URLs intended to be used
                to surface additional documentation, dashboards, etc.
              items:
                description: Link contains information about an URL to surface documentation,
                  dashboards, etc.
                properties:
                  description:
                    description: Description is human readable content explaining
                      the purpose of the link.
                    type: string
                  url:
                    description: Url typically points at a website address.
                    type: string
                type: object
              type: array
            maintainers:
              description: Maintainers is an optional list of maintainers of the application.
                The maintainers in this list maintain the the source code, images,
                and package for the application.
              items:
                description: ContactData contains information about an individual
                  or organization.
                properties:
                  email:
                    description: Email is the email address.
                    type: string
                  name:
                    description: Name is the descriptive name.
                    type: string
                  url:
                    description: Url could typically be a website address.
                    type: string
                type: object
              type: array
            owners:
              description: Owners is an optional list of the owners of the installed
                application. The owners of the application should be contacted in
                the event of a orderned or unorderned disruption affecting the application.
              items:
                description: ContactData contains information about an individual
                  or organization.
                properties:
                  email:
                    description: Email is the email address.
                    type: string
                  name:
                    description: Name is the descriptive name.
                    type: string
                  url:
                    description: Url could typically be a website address.
                    type: string
                type: object
              type: array
            packages:
              items:
                properties:
                  chart:
                    properties:
                      feature:
                        description: 'One sentence description of feature provided
                          by this addon TODO: Move to a different struct instead of
                          ref'
                        type: string
                      multiSelect:
                        type: boolean
                      name:
                        type: string
                      url:
                        type: string
                      versions:
                        items:
                          properties:
                            selected:
                              type: boolean
                            version:
                              type: string
                          required:
                          - version
                          type: object
                        type: array
                    required:
                    - feature
                    - name
                    - url
                    - versions
                    type: object
                  required:
                    type: boolean
                required:
                - chart
                type: object
              type: array
          required:
          - packages
          type: object
        status:
          properties:
            observedGeneration:
              description: ObservedGeneration is the most recent generation observed
                for this resource. It corresponds to the resource's generation, which
                is updated on mutation by the API Server.
              format: int64
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
