apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: searchlight
  name: bundles.kubepack.dev
spec:
  group: kubepack.dev
  names:
    categories:
    - kubepack
    - appscode
    kind: Bundle
    listKind: BundleList
    plural: bundles
    singular: bundle
  preserveUnknownFields: false
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              items:
                properties:
                  name:
                    type: string
                  url:
                    type: string
                  versions:
                    items:
                      type: string
                    type: array
                required:
                - name
                - url
                - versions
                type: object
              type: array
            packages:
              items:
                properties:
                  chart:
                    properties:
                      name:
                        type: string
                      url:
                        type: string
                      versions:
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - url
                    - versions
                    type: object
                  required:
                    type: boolean
                required:
                - chart
                - required
                type: object
              type: array
          required:
          - addons
          - packages
          type: object
        status:
          properties:
            observedGeneration:
              description: ObservedGeneration is the most recent generation observed
                for this resource. It corresponds to the resource's generation, which
                is updated on mutation by the API Server.
              format: int64
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
