kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
# the control ordere node
- role: control-plane
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
