apiVersion: kubepack.com/v1alpha1
kind: Order
metadata:
  creationTimestamp: null
  name: kubedb-bundle
spec:
  items:
  - chart:
      bundle:
        name: kubedb-bundle
        url: https://kubepack-testcharts.storage.googleapis.com
        version: v0.13.0-rc.2
      name: kubedb
      namespace: kube-system
      releaseName: kubedb
      url: https://charts.appscode.com/stable/
      version: v0.13.0-rc.0
  - chart:
      bundle:
        name: kubedb-bundle
        url: https://kubepack-testcharts.storage.googleapis.com
        version: v0.13.0-rc.2
      name: kubedb-catalog
      namespace: kube-system
      releaseName: kubedb-catalog
      url: https://charts.appscode.com/stable/
      version: v0.13.0-rc.0
status: {}
